storedQuantity: DoseRate
detectors:
  det1:
    Mass: "10 kg"
  det2:
    Mass: "20 kg"

plugins:
  PlotMaker:
    plot1:
      quantity: DoseRate
      type: 2D
      xtitle: my_x_title
      ytitle: my_y_title
      ztitle: my_z_title
